### ISSUE TITLE
Add one-to-one mapping for multiple mqtt topics 

### ISSUE THREAD

**Issue by shu-bham** [kaiwaehner/kafka-connect-iot-mqtt-connector-example#8]
Is one-to-one mapping now available for multiple mqtt topics ?
Ex:
`"mqtt.topics" : "temperature,humidity"`
`"kafka.topics" : "mqtt.temperature,mqtt.humidity"`
so that `temperature` corresponds to `mqtt.temperature` and `humidity` to `mqtt.humidity`.

_Originally posted by @shu-bham in https://github.com/kaiwaehner/kafka-connect-iot-mqtt-connector-example/commit/c1b9bd79194a6dfdc8cc25259ac522600fc49d5a#commitcomment-31846708_

**Update:**
I checked the above config and found it not working. Pls add the functionality for one-to-one mapping of mqtt topic to kafka-topic. Thank You

**Comment by kaiwaehner** [comment]
@shu-bham 

I doublechecked with engineering: **Mapping from many MQTT topics to one Kafka topic is possible today already**. It is different than it is solved in MQTT Proxy, though (where you use a regex to define this mapping).

With Kafka Connect and MQTT Connector, you use Single Message Transforms (SMT, https://docs.confluent.io/current/connect/transforms/index.html) to do this.

There is a new ExtractTopic SMT that can take keys or values (or specific fields within them) to populate the topic field: https://docs.confluent.io/current/connect/transforms/extracttopic.html. By default the source connector puts the Mqtt topic name into the key of the message. With this SMT you can push that key back into the topic name of the message.

You are correct: The config now uses 'kafka.topic' instead of 'kafka.topics'. Also took me some time to find this out :-) I also discussed this with our engineering. Confluent will change and improve the release cycle for Confluent Hub components and also add things like release notes and migration guides for future releases.

**Comment by shu-bham** [comment]
Thank you for replying. The ExtractTopic SMT was something I needed for a long time. Thanks for pointing that out.
